project_id = "ipjidjijilhpblxrnaeg"

[functions.validate-credentials]
verify_jwt = true

[functions.pos-fudo]
verify_jwt = false

[functions.pos-maxirest]
verify_jwt = false

[functions.pos-bistrosoft]
verify_jwt = false

[functions.pos-sync]
verify_jwt = false

[functions.send-invite]
verify_jwt = true

[functions.pos-save-credentials]
verify_jwt = true

[functions.pos-verify-credentials]
verify_jwt = true

[functions.pos-sync-daily]
verify_jwt = false

[functions.pos-sync-ui]
verify_jwt = true
