// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipjidjijilhpblxrnaeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwamlkamlqaWxocGJseHJuYWVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NjQ1NjUsImV4cCI6MjA3MDI0MDU2NX0.fzYgzPAWcz2bJE3zfxXEVUE3vbdf2cHa0ZSuVBLZ7vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});